import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";

const Josefin_sans = Josefin_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Resonance",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme : light)",
        url: "/logo-dark.svg",
        href: "/logo-dark.svg",
      },
      {
        media: "(prefers-color-scheme : dark)",
        url: "/logo-white.svg",
        href: "/logo-white.svg",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Josefin_sans.className} ${Josefin_sans.style} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
